let fffiles = `
./.ArgsEnv
/embed-env/lib/R/etc/repositories
/embed-env/lib/R/etc/Makeconf
/embed-env/lib/R/etc/Renviron
/embed-env/lib/R/etc/javaconf
/embed-env/lib/R/etc/ldpaths
/embed-env/lib/R/include/R_ext/Altrep.h
/embed-env/lib/R/include/R_ext/Applic.h
/embed-env/lib/R/include/R_ext/Arith.h
/embed-env/lib/R/include/R_ext/BLAS.h
/embed-env/lib/R/include/R_ext/Boolean.h
/embed-env/lib/R/include/R_ext/Callbacks.h
/embed-env/lib/R/include/R_ext/Complex.h
/embed-env/lib/R/include/R_ext/Connections.h
/embed-env/lib/R/include/R_ext/Constants.h
/embed-env/lib/R/include/R_ext/Error.h
/embed-env/lib/R/include/R_ext/GetX11Image.h
/embed-env/lib/R/include/R_ext/GraphicsDevice.h
/embed-env/lib/R/include/R_ext/GraphicsEngine.h
/embed-env/lib/R/include/R_ext/Itermacros.h
/embed-env/lib/R/include/R_ext/Lapack.h
/embed-env/lib/R/include/R_ext/Linpack.h
/embed-env/lib/R/include/R_ext/MathThreads.h
/embed-env/lib/R/include/R_ext/Memory.h
/embed-env/lib/R/include/R_ext/QuartzDevice.h
/embed-env/lib/R/include/R_ext/Parse.h
/embed-env/lib/R/include/R_ext/Print.h
/embed-env/lib/R/include/R_ext/PrtUtil.h
/embed-env/lib/R/include/R_ext/RS.h
/embed-env/lib/R/include/R_ext/Rallocators.h
/embed-env/lib/R/include/R_ext/Random.h
/embed-env/lib/R/include/R_ext/Rdynload.h
/embed-env/lib/R/include/R_ext/Riconv.h
/embed-env/lib/R/include/R_ext/RStartup.h
/embed-env/lib/R/include/R_ext/Utils.h
/embed-env/lib/R/include/R_ext/eventloop.h
/embed-env/lib/R/include/R_ext/libextern.h
/embed-env/lib/R/include/R_ext/stats_package.h
/embed-env/lib/R/include/R_ext/stats_stubs.h
/embed-env/lib/R/include/R_ext/Visibility.h
/embed-env/lib/R/include/R.h
/embed-env/lib/R/include/Rdefines.h
/embed-env/lib/R/include/Rembedded.h
/embed-env/lib/R/include/Rinternals.h
/embed-env/lib/R/include/Rinterface.h
/embed-env/lib/R/include/Rconfig.h
/embed-env/lib/R/include/Rmath.h
/embed-env/lib/R/include/Rversion.h
/embed-env/lib/R/lib/libR.a
/embed-env/lib/R/lib/libRblas.so
/embed-env/lib/R/lib/libRlapack.so
/embed-env/lib/R/library/base/CITATION
/embed-env/lib/R/library/base/DESCRIPTION
/embed-env/lib/R/library/base/INDEX
/embed-env/lib/R/library/base/Meta/Rd.rds
/embed-env/lib/R/library/base/Meta/demo.rds
/embed-env/lib/R/library/base/Meta/features.rds
/embed-env/lib/R/library/base/Meta/hsearch.rds
/embed-env/lib/R/library/base/Meta/links.rds
/embed-env/lib/R/library/base/Meta/package.rds
/embed-env/lib/R/library/base/R/Rprofile
/embed-env/lib/R/library/base/R/base
/embed-env/lib/R/library/base/R/base.rdb
/embed-env/lib/R/library/base/R/base.rdx
/embed-env/lib/R/library/base/demo/error.catching.R
/embed-env/lib/R/library/base/demo/is.things.R
/embed-env/lib/R/library/base/demo/recursion.R
/embed-env/lib/R/library/base/demo/scoping.R
/embed-env/lib/R/library/base/help/AnIndex
/embed-env/lib/R/library/base/help/aliases.rds
/embed-env/lib/R/library/base/help/base.rdb
/embed-env/lib/R/library/base/help/base.rdx
/embed-env/lib/R/library/base/help/paths.rds
/embed-env/lib/R/library/base/html/00Index.html
/embed-env/lib/R/library/base/html/R.css
/embed-env/lib/R/library/compiler/DESCRIPTION
/embed-env/lib/R/library/compiler/INDEX
/embed-env/lib/R/library/compiler/Meta/Rd.rds
/embed-env/lib/R/library/compiler/Meta/features.rds
/embed-env/lib/R/library/compiler/Meta/hsearch.rds
/embed-env/lib/R/library/compiler/Meta/links.rds
/embed-env/lib/R/library/compiler/Meta/nsInfo.rds
/embed-env/lib/R/library/compiler/Meta/package.rds
/embed-env/lib/R/library/compiler/NAMESPACE
/embed-env/lib/R/library/compiler/R/compiler
/embed-env/lib/R/library/compiler/R/compiler.rdb
/embed-env/lib/R/library/compiler/R/compiler.rdx
/embed-env/lib/R/library/compiler/help/AnIndex
/embed-env/lib/R/library/compiler/help/aliases.rds
/embed-env/lib/R/library/compiler/help/compiler.rdb
/embed-env/lib/R/library/compiler/help/compiler.rdx
/embed-env/lib/R/library/compiler/help/paths.rds
/embed-env/lib/R/library/compiler/html/00Index.html
/embed-env/lib/R/library/compiler/html/R.css
/embed-env/lib/R/library/datasets/DESCRIPTION
/embed-env/lib/R/library/datasets/INDEX
/embed-env/lib/R/library/datasets/Meta/Rd.rds
/embed-env/lib/R/library/datasets/Meta/data.rds
/embed-env/lib/R/library/datasets/Meta/features.rds
/embed-env/lib/R/library/datasets/Meta/hsearch.rds
/embed-env/lib/R/library/datasets/Meta/links.rds
/embed-env/lib/R/library/datasets/Meta/nsInfo.rds
/embed-env/lib/R/library/datasets/Meta/package.rds
/embed-env/lib/R/library/datasets/NAMESPACE
/embed-env/lib/R/library/datasets/data/AirPassengers.R
/embed-env/lib/R/library/datasets/data/BJsales.R
/embed-env/lib/R/library/datasets/data/BOD.R
/embed-env/lib/R/library/datasets/data/CO2.rda
/embed-env/lib/R/library/datasets/data/ChickWeight.R
/embed-env/lib/R/library/datasets/data/DNase.R
/embed-env/lib/R/library/datasets/data/EuStockMarkets.R
/embed-env/lib/R/library/datasets/data/Formaldehyde.R
/embed-env/lib/R/library/datasets/data/HairEyeColor.R
/embed-env/lib/R/library/datasets/data/Harman23.cor.R
/embed-env/lib/R/library/datasets/data/Harman74.cor.R
/embed-env/lib/R/library/datasets/data/Indometh.R
/embed-env/lib/R/library/datasets/data/InsectSprays.R
/embed-env/lib/R/library/datasets/data/JohnsonJohnson.R
/embed-env/lib/R/library/datasets/data/LakeHuron.R
/embed-env/lib/R/library/datasets/data/LifeCycleSavings.R
/embed-env/lib/R/library/datasets/data/Loblolly.R
/embed-env/lib/R/library/datasets/data/Nile.R
/embed-env/lib/R/library/datasets/data/Orange.R
/embed-env/lib/R/library/datasets/data/OrchardSprays.R
/embed-env/lib/R/library/datasets/data/PlantGrowth.R
/embed-env/lib/R/library/datasets/data/Puromycin.R
/embed-env/lib/R/library/datasets/data/Rdata.rdb
/embed-env/lib/R/library/datasets/data/Rdata.rds
/embed-env/lib/R/library/datasets/data/Rdata.rdx
/embed-env/lib/R/library/datasets/data/Seatbelts.R
/embed-env/lib/R/library/datasets/data/Theoph.R
/embed-env/lib/R/library/datasets/data/Titanic.R
/embed-env/lib/R/library/datasets/data/ToothGrowth.R
/embed-env/lib/R/library/datasets/data/UCBAdmissions.R
/embed-env/lib/R/library/datasets/data/UKDriverDeaths.R
/embed-env/lib/R/library/datasets/data/UKLungDeaths.R
/embed-env/lib/R/library/datasets/data/UKgas.R
/embed-env/lib/R/library/datasets/data/USAccDeaths.R
/embed-env/lib/R/library/datasets/data/USArrests.tab
/embed-env/lib/R/library/datasets/data/USJudgeRatings.R
/embed-env/lib/R/library/datasets/data/USPersonalExpenditure.R
/embed-env/lib/R/library/datasets/data/UScitiesD.rda
/embed-env/lib/R/library/datasets/data/VADeaths.R
/embed-env/lib/R/library/datasets/data/WWWusage.R
/embed-env/lib/R/library/datasets/data/WorldPhones.R
/embed-env/lib/R/library/datasets/data/ability.cov.R
/embed-env/lib/R/library/datasets/data/airmiles.R
/embed-env/lib/R/library/datasets/data/airquality.tab
/embed-env/lib/R/library/datasets/data/anscombe.R
/embed-env/lib/R/library/datasets/data/attenu.R
/embed-env/lib/R/library/datasets/data/attitude.R
/embed-env/lib/R/library/datasets/data/austres.R
/embed-env/lib/R/library/datasets/data/beavers.R
/embed-env/lib/R/library/datasets/data/cars.R
/embed-env/lib/R/library/datasets/data/chickwts.R
/embed-env/lib/R/library/datasets/data/co2.R
/embed-env/lib/R/library/datasets/data/crimtab.rda
/embed-env/lib/R/library/datasets/data/discoveries.R
/embed-env/lib/R/library/datasets/data/esoph.R
/embed-env/lib/R/library/datasets/data/euro.R
/embed-env/lib/R/library/datasets/data/eurodist.R
/embed-env/lib/R/library/datasets/data/faithful.R
/embed-env/lib/R/library/datasets/data/freeny.R
/embed-env/lib/R/library/datasets/data/infert.R
/embed-env/lib/R/library/datasets/data/iris.R
/embed-env/lib/R/library/datasets/data/iris3.R
/embed-env/lib/R/library/datasets/data/islands.R
/embed-env/lib/R/library/datasets/data/lh.R
/embed-env/lib/R/library/datasets/data/longley.R
/embed-env/lib/R/library/datasets/data/lynx.R
/embed-env/lib/R/library/datasets/data/morley.tab
/embed-env/lib/R/library/datasets/data/mtcars.R
/embed-env/lib/R/library/datasets/data/nhtemp.R
/embed-env/lib/R/library/datasets/data/nottem.R
/embed-env/lib/R/library/datasets/data/npk.rda
/embed-env/lib/R/library/datasets/data/occupationalStatus.R
/embed-env/lib/R/library/datasets/data/precip.R
/embed-env/lib/R/library/datasets/data/presidents.R
/embed-env/lib/R/library/datasets/data/pressure.R
/embed-env/lib/R/library/datasets/data/quakes.tab
/embed-env/lib/R/library/datasets/data/randu.R
/embed-env/lib/R/library/datasets/data/rivers.R
/embed-env/lib/R/library/datasets/data/rock.tab
/embed-env/lib/R/library/datasets/data/sleep.R
/embed-env/lib/R/library/datasets/data/stackloss.R
/embed-env/lib/R/library/datasets/data/state.R
/embed-env/lib/R/library/datasets/data/sunspot.month.R
/embed-env/lib/R/library/datasets/data/sunspot.year.R
/embed-env/lib/R/library/datasets/data/sunspots.R
/embed-env/lib/R/library/datasets/data/swiss.tab
/embed-env/lib/R/library/datasets/data/treering.R
/embed-env/lib/R/library/datasets/data/trees.R
/embed-env/lib/R/library/datasets/data/uspop.R
/embed-env/lib/R/library/datasets/data/volcano.R
/embed-env/lib/R/library/datasets/data/warpbreaks.R
/embed-env/lib/R/library/datasets/data/women.R
/embed-env/lib/R/library/datasets/help/AnIndex
/embed-env/lib/R/library/datasets/help/aliases.rds
/embed-env/lib/R/library/datasets/help/datasets.rdb
/embed-env/lib/R/library/datasets/help/datasets.rdx
/embed-env/lib/R/library/datasets/help/paths.rds
/embed-env/lib/R/library/datasets/html/00Index.html
/embed-env/lib/R/library/datasets/html/R.css
/embed-env/lib/R/library/grDevices/DESCRIPTION
/embed-env/lib/R/library/grDevices/INDEX
/embed-env/lib/R/library/grDevices/Meta/Rd.rds
/embed-env/lib/R/library/grDevices/Meta/demo.rds
/embed-env/lib/R/library/grDevices/Meta/features.rds
/embed-env/lib/R/library/grDevices/Meta/hsearch.rds
/embed-env/lib/R/library/grDevices/Meta/links.rds
/embed-env/lib/R/library/grDevices/Meta/nsInfo.rds
/embed-env/lib/R/library/grDevices/Meta/package.rds
/embed-env/lib/R/library/grDevices/NAMESPACE
/embed-env/lib/R/library/grDevices/R/grDevices
/embed-env/lib/R/library/grDevices/R/grDevices.rdb
/embed-env/lib/R/library/grDevices/R/grDevices.rdx
/embed-env/lib/R/library/grDevices/afm/ArialMT-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/ArialMT-BoldItalic.afm.gz
/embed-env/lib/R/library/grDevices/afm/ArialMT-Italic.afm.gz
/embed-env/lib/R/library/grDevices/afm/ArialMT.afm.gz
/embed-env/lib/R/library/grDevices/afm/CM_boldx_10.afm.gz
/embed-env/lib/R/library/grDevices/afm/CM_boldx_italic_10.afm.gz
/embed-env/lib/R/library/grDevices/afm/CM_italic_10.afm.gz
/embed-env/lib/R/library/grDevices/afm/CM_regular_10.afm.gz
/embed-env/lib/R/library/grDevices/afm/CM_symbol_10.afm.gz
/embed-env/lib/R/library/grDevices/afm/Courier-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/Courier-BoldOblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/Courier-Oblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/Courier.afm.gz
/embed-env/lib/R/library/grDevices/afm/Helvetica-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/Helvetica-BoldOblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/Helvetica-Oblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/Helvetica.afm.gz
/embed-env/lib/R/library/grDevices/afm/LICENSE.LPPL
/embed-env/lib/R/library/grDevices/afm/MustRead.html
/embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-BoldItalic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Italic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Regular.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusRoman-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusRoman-BoldItalic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusRoman-Italic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusRoman-Regular.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-BoldItalic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-BoldOblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-Italic.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-Oblique.afm.gz
/embed-env/lib/R/library/grDevices/afm/NimbusSans-Regular.afm.gz
/embed-env/lib/R/library/grDevices/afm/README
/embed-env/lib/R/library/grDevices/afm/StandardSymbolsPS.afm.gz
/embed-env/lib/R/library/grDevices/afm/Symbol.afm.gz
/embed-env/lib/R/library/grDevices/afm/Times-Bold.afm.gz
/embed-env/lib/R/library/grDevices/afm/Times-BoldItalic.afm.gz
/embed-env/lib/R/library/grDevices/afm/Times-Italic.afm.gz
/embed-env/lib/R/library/grDevices/afm/Times-Roman.afm.gz
/embed-env/lib/R/library/grDevices/afm/ZapfDingbats.afm.gz
/embed-env/lib/R/library/grDevices/afm/a010013l.afm.gz
/embed-env/lib/R/library/grDevices/afm/a010015l.afm.gz
/embed-env/lib/R/library/grDevices/afm/a010033l.afm.gz
/embed-env/lib/R/library/grDevices/afm/a010035l.afm.gz
/embed-env/lib/R/library/grDevices/afm/agd_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/agdo____.afm.gz
/embed-env/lib/R/library/grDevices/afm/agw_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/agwo____.afm.gz
/embed-env/lib/R/library/grDevices/afm/b018012l.afm.gz
/embed-env/lib/R/library/grDevices/afm/b018015l.afm.gz
/embed-env/lib/R/library/grDevices/afm/b018032l.afm.gz
/embed-env/lib/R/library/grDevices/afm/b018035l.afm.gz
/embed-env/lib/R/library/grDevices/afm/bkd_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/bkdi____.afm.gz
/embed-env/lib/R/library/grDevices/afm/bkl_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/bkli____.afm.gz
/embed-env/lib/R/library/grDevices/afm/c059013l.afm.gz
/embed-env/lib/R/library/grDevices/afm/c059016l.afm.gz
/embed-env/lib/R/library/grDevices/afm/c059033l.afm.gz
/embed-env/lib/R/library/grDevices/afm/c059036l.afm.gz
/embed-env/lib/R/library/grDevices/afm/cmbxti10.afm.gz
/embed-env/lib/R/library/grDevices/afm/cmti10.afm.gz
/embed-env/lib/R/library/grDevices/afm/cob_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/cobo____.afm.gz
/embed-env/lib/R/library/grDevices/afm/com_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/coo_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hv______.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvb_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvbo____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvn_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvnb____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvnbo___.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvno____.afm.gz
/embed-env/lib/R/library/grDevices/afm/hvo_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019003l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019004l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019023l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019024l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019043l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019044l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019063l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n019064l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n021003l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n021004l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n021023l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n021024l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n022003l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n022004l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n022023l.afm.gz
/embed-env/lib/R/library/grDevices/afm/n022024l.afm.gz
/embed-env/lib/R/library/grDevices/afm/ncb_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/ncbi____.afm.gz
/embed-env/lib/R/library/grDevices/afm/nci_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/ncr_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/p052003l.afm.gz
/embed-env/lib/R/library/grDevices/afm/p052004l.afm.gz
/embed-env/lib/R/library/grDevices/afm/p052023l.afm.gz
/embed-env/lib/R/library/grDevices/afm/p052024l.afm.gz
/embed-env/lib/R/library/grDevices/afm/pob_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/pobi____.afm.gz
/embed-env/lib/R/library/grDevices/afm/poi_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/por_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/s050000l.afm.gz
/embed-env/lib/R/library/grDevices/afm/sy______.afm.gz
/embed-env/lib/R/library/grDevices/afm/tib_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/tibi____.afm.gz
/embed-env/lib/R/library/grDevices/afm/tii_____.afm.gz
/embed-env/lib/R/library/grDevices/afm/tir_____.afm.gz
/embed-env/lib/R/library/grDevices/demo/colors.R
/embed-env/lib/R/library/grDevices/demo/hclColors.R
/embed-env/lib/R/library/grDevices/enc/AdobeStd.enc
/embed-env/lib/R/library/grDevices/enc/AdobeSym.enc
/embed-env/lib/R/library/grDevices/enc/CP1250.enc
/embed-env/lib/R/library/grDevices/enc/CP1251.enc
/embed-env/lib/R/library/grDevices/enc/CP1253.enc
/embed-env/lib/R/library/grDevices/enc/CP1257.enc
/embed-env/lib/R/library/grDevices/enc/Cyrillic.enc
/embed-env/lib/R/library/grDevices/enc/Greek.enc
/embed-env/lib/R/library/grDevices/enc/ISOLatin1.enc
/embed-env/lib/R/library/grDevices/enc/ISOLatin2.enc
/embed-env/lib/R/library/grDevices/enc/ISOLatin7.enc
/embed-env/lib/R/library/grDevices/enc/ISOLatin9.enc
/embed-env/lib/R/library/grDevices/enc/KOI8-R.enc
/embed-env/lib/R/library/grDevices/enc/KOI8-U.enc
/embed-env/lib/R/library/grDevices/enc/PDFDoc.enc
/embed-env/lib/R/library/grDevices/enc/TeXtext.enc
/embed-env/lib/R/library/grDevices/enc/WinAnsi.enc
/embed-env/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
/embed-env/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-Medium.ttf
/embed-env/lib/R/library/grDevices/fonts/Roboto/LICENSE.txt
/embed-env/lib/R/library/grDevices/fonts/Roboto/Roboto-Medium.ttf
/embed-env/lib/R/library/grDevices/help/AnIndex
/embed-env/lib/R/library/grDevices/help/aliases.rds
/embed-env/lib/R/library/grDevices/help/grDevices.rdb
/embed-env/lib/R/library/grDevices/help/grDevices.rdx
/embed-env/lib/R/library/grDevices/help/paths.rds
/embed-env/lib/R/library/grDevices/html/00Index.html
/embed-env/lib/R/library/grDevices/html/R.css
/embed-env/lib/R/library/grDevices/icc/srgb
/embed-env/lib/R/library/grDevices/icc/srgb.flate
/embed-env/lib/R/library/grDevices/libs/grDevices.so
/embed-env/lib/R/library/graphics/DESCRIPTION
/embed-env/lib/R/library/graphics/INDEX
/embed-env/lib/R/library/graphics/Meta/Rd.rds
/embed-env/lib/R/library/graphics/Meta/demo.rds
/embed-env/lib/R/library/graphics/Meta/features.rds
/embed-env/lib/R/library/graphics/Meta/hsearch.rds
/embed-env/lib/R/library/graphics/Meta/links.rds
/embed-env/lib/R/library/graphics/Meta/nsInfo.rds
/embed-env/lib/R/library/graphics/Meta/package.rds
/embed-env/lib/R/library/graphics/NAMESPACE
/embed-env/lib/R/library/graphics/R/graphics
/embed-env/lib/R/library/graphics/R/graphics.rdb
/embed-env/lib/R/library/graphics/R/graphics.rdx
/embed-env/lib/R/library/graphics/demo/Hershey.R
/embed-env/lib/R/library/graphics/demo/Japanese.R
/embed-env/lib/R/library/graphics/demo/graphics.R
/embed-env/lib/R/library/graphics/demo/image.R
/embed-env/lib/R/library/graphics/demo/persp.R
/embed-env/lib/R/library/graphics/demo/plotmath.R
/embed-env/lib/R/library/graphics/help/AnIndex
/embed-env/lib/R/library/graphics/help/aliases.rds
/embed-env/lib/R/library/graphics/help/figures/mai.pdf
/embed-env/lib/R/library/graphics/help/figures/mai.png
/embed-env/lib/R/library/graphics/help/figures/oma.pdf
/embed-env/lib/R/library/graphics/help/figures/oma.png
/embed-env/lib/R/library/graphics/help/figures/pch.pdf
/embed-env/lib/R/library/graphics/help/figures/pch.png
/embed-env/lib/R/library/graphics/help/figures/pch.svg
/embed-env/lib/R/library/graphics/help/graphics.rdb
/embed-env/lib/R/library/graphics/help/graphics.rdx
/embed-env/lib/R/library/graphics/help/paths.rds
/embed-env/lib/R/library/graphics/html/00Index.html
/embed-env/lib/R/library/graphics/html/R.css
/embed-env/lib/R/library/graphics/libs/graphics.so
/embed-env/lib/R/library/grid/DESCRIPTION
/embed-env/lib/R/library/grid/INDEX
/embed-env/lib/R/library/grid/Meta/Rd.rds
/embed-env/lib/R/library/grid/Meta/features.rds
/embed-env/lib/R/library/grid/Meta/hsearch.rds
/embed-env/lib/R/library/grid/Meta/links.rds
/embed-env/lib/R/library/grid/Meta/nsInfo.rds
/embed-env/lib/R/library/grid/Meta/package.rds
/embed-env/lib/R/library/grid/NAMESPACE
/embed-env/lib/R/library/grid/R/grid
/embed-env/lib/R/library/grid/R/grid.rdb
/embed-env/lib/R/library/grid/R/grid.rdx
/embed-env/lib/R/library/grid/doc/DivByZero.txt
/embed-env/lib/R/library/grid/doc/changes.txt
/embed-env/lib/R/library/grid/doc/displaylist.pdf
/embed-env/lib/R/library/grid/doc/frame.pdf
/embed-env/lib/R/library/grid/doc/grid.pdf
/embed-env/lib/R/library/grid/doc/grobs.pdf
/embed-env/lib/R/library/grid/doc/interactive.pdf
/embed-env/lib/R/library/grid/doc/locndimn.pdf
/embed-env/lib/R/library/grid/doc/moveline.pdf
/embed-env/lib/R/library/grid/doc/nonfinite.pdf
/embed-env/lib/R/library/grid/doc/plotexample.pdf
/embed-env/lib/R/library/grid/doc/rotated.pdf
/embed-env/lib/R/library/grid/doc/saveload.pdf
/embed-env/lib/R/library/grid/doc/sharing.pdf
/embed-env/lib/R/library/grid/doc/viewports.pdf
/embed-env/lib/R/library/grid/help/AnIndex
/embed-env/lib/R/library/grid/help/aliases.rds
/embed-env/lib/R/library/grid/help/grid.rdb
/embed-env/lib/R/library/grid/help/grid.rdx
/embed-env/lib/R/library/grid/help/paths.rds
/embed-env/lib/R/library/grid/html/00Index.html
/embed-env/lib/R/library/grid/html/R.css
/embed-env/lib/R/library/grid/libs/grid.so
/embed-env/lib/R/library/methods/DESCRIPTION
/embed-env/lib/R/library/methods/INDEX
/embed-env/lib/R/library/methods/Meta/Rd.rds
/embed-env/lib/R/library/methods/Meta/features.rds
/embed-env/lib/R/library/methods/Meta/hsearch.rds
/embed-env/lib/R/library/methods/Meta/links.rds
/embed-env/lib/R/library/methods/Meta/nsInfo.rds
/embed-env/lib/R/library/methods/Meta/package.rds
/embed-env/lib/R/library/methods/NAMESPACE
/embed-env/lib/R/library/methods/R/methods
/embed-env/lib/R/library/methods/R/methods.rdb
/embed-env/lib/R/library/methods/R/methods.rdx
/embed-env/lib/R/library/methods/help/AnIndex
/embed-env/lib/R/library/methods/help/aliases.rds
/embed-env/lib/R/library/methods/help/methods.rdb
/embed-env/lib/R/library/methods/help/methods.rdx
/embed-env/lib/R/library/methods/help/paths.rds
/embed-env/lib/R/library/methods/html/00Index.html
/embed-env/lib/R/library/methods/html/R.css
/embed-env/lib/R/library/methods/libs/methods.so
/embed-env/lib/R/library/parallel/DESCRIPTION
/embed-env/lib/R/library/parallel/INDEX
/embed-env/lib/R/library/parallel/Meta/Rd.rds
/embed-env/lib/R/library/parallel/Meta/features.rds
/embed-env/lib/R/library/parallel/Meta/hsearch.rds
/embed-env/lib/R/library/parallel/Meta/links.rds
/embed-env/lib/R/library/parallel/Meta/nsInfo.rds
/embed-env/lib/R/library/parallel/Meta/package.rds
/embed-env/lib/R/library/parallel/NAMESPACE
/embed-env/lib/R/library/parallel/R/parallel
/embed-env/lib/R/library/parallel/R/parallel.rdb
/embed-env/lib/R/library/parallel/R/parallel.rdx
/embed-env/lib/R/library/parallel/doc/parallel.pdf
/embed-env/lib/R/library/parallel/help/AnIndex
/embed-env/lib/R/library/parallel/help/aliases.rds
/embed-env/lib/R/library/parallel/help/parallel.rdb
/embed-env/lib/R/library/parallel/help/parallel.rdx
/embed-env/lib/R/library/parallel/help/paths.rds
/embed-env/lib/R/library/parallel/html/00Index.html
/embed-env/lib/R/library/parallel/html/R.css
/embed-env/lib/R/library/parallel/libs/parallel.so
/embed-env/lib/R/library/splines/DESCRIPTION
/embed-env/lib/R/library/splines/INDEX
/embed-env/lib/R/library/splines/Meta/Rd.rds
/embed-env/lib/R/library/splines/Meta/features.rds
/embed-env/lib/R/library/splines/Meta/hsearch.rds
/embed-env/lib/R/library/splines/Meta/links.rds
/embed-env/lib/R/library/splines/Meta/nsInfo.rds
/embed-env/lib/R/library/splines/Meta/package.rds
/embed-env/lib/R/library/splines/NAMESPACE
/embed-env/lib/R/library/splines/R/splines
/embed-env/lib/R/library/splines/R/splines.rdb
/embed-env/lib/R/library/splines/R/splines.rdx
/embed-env/lib/R/library/splines/help/AnIndex
/embed-env/lib/R/library/splines/help/aliases.rds
/embed-env/lib/R/library/splines/help/paths.rds
/embed-env/lib/R/library/splines/help/splines.rdb
/embed-env/lib/R/library/splines/help/splines.rdx
/embed-env/lib/R/library/splines/html/00Index.html
/embed-env/lib/R/library/splines/html/R.css
/embed-env/lib/R/library/splines/libs/splines.so
/embed-env/lib/R/library/stats/COPYRIGHTS.modreg
/embed-env/lib/R/library/stats/DESCRIPTION
/embed-env/lib/R/library/stats/INDEX
/embed-env/lib/R/library/stats/Meta/Rd.rds
/embed-env/lib/R/library/stats/Meta/demo.rds
/embed-env/lib/R/library/stats/Meta/features.rds
/embed-env/lib/R/library/stats/Meta/hsearch.rds
/embed-env/lib/R/library/stats/Meta/links.rds
/embed-env/lib/R/library/stats/Meta/nsInfo.rds
/embed-env/lib/R/library/stats/Meta/package.rds
/embed-env/lib/R/library/stats/NAMESPACE
/embed-env/lib/R/library/stats/R/stats
/embed-env/lib/R/library/stats/R/stats.rdb
/embed-env/lib/R/library/stats/R/stats.rdx
/embed-env/lib/R/library/stats/SOURCES.ts
/embed-env/lib/R/library/stats/demo/glm.vr.R
/embed-env/lib/R/library/stats/demo/lm.glm.R
/embed-env/lib/R/library/stats/demo/nlm.R
/embed-env/lib/R/library/stats/demo/smooth.R
/embed-env/lib/R/library/stats/help/AnIndex
/embed-env/lib/R/library/stats/help/aliases.rds
/embed-env/lib/R/library/stats/help/paths.rds
/embed-env/lib/R/library/stats/help/stats.rdb
/embed-env/lib/R/library/stats/help/stats.rdx
/embed-env/lib/R/library/stats/html/00Index.html
/embed-env/lib/R/library/stats/html/R.css
/embed-env/lib/R/library/stats/libs/stats.so
/embed-env/lib/R/library/stats4/DESCRIPTION
/embed-env/lib/R/library/stats4/INDEX
/embed-env/lib/R/library/stats4/Meta/Rd.rds
/embed-env/lib/R/library/stats4/Meta/features.rds
/embed-env/lib/R/library/stats4/Meta/hsearch.rds
/embed-env/lib/R/library/stats4/Meta/links.rds
/embed-env/lib/R/library/stats4/Meta/nsInfo.rds
/embed-env/lib/R/library/stats4/Meta/package.rds
/embed-env/lib/R/library/stats4/NAMESPACE
/embed-env/lib/R/library/stats4/R/stats4
/embed-env/lib/R/library/stats4/R/stats4.rdb
/embed-env/lib/R/library/stats4/R/stats4.rdx
/embed-env/lib/R/library/stats4/help/AnIndex
/embed-env/lib/R/library/stats4/help/aliases.rds
/embed-env/lib/R/library/stats4/help/paths.rds
/embed-env/lib/R/library/stats4/help/stats4.rdb
/embed-env/lib/R/library/stats4/help/stats4.rdx
/embed-env/lib/R/library/stats4/html/00Index.html
/embed-env/lib/R/library/stats4/html/R.css
/embed-env/lib/R/library/tcltk/DESCRIPTION
/embed-env/lib/R/library/tcltk/INDEX
/embed-env/lib/R/library/tcltk/Meta/Rd.rds
/embed-env/lib/R/library/tcltk/Meta/demo.rds
/embed-env/lib/R/library/tcltk/Meta/features.rds
/embed-env/lib/R/library/tcltk/Meta/hsearch.rds
/embed-env/lib/R/library/tcltk/Meta/links.rds
/embed-env/lib/R/library/tcltk/Meta/nsInfo.rds
/embed-env/lib/R/library/tcltk/Meta/package.rds
/embed-env/lib/R/library/tcltk/NAMESPACE
/embed-env/lib/R/library/tcltk/R/tcltk
/embed-env/lib/R/library/tcltk/R/tcltk.rdb
/embed-env/lib/R/library/tcltk/R/tcltk.rdx
/embed-env/lib/R/library/tcltk/demo/tkcanvas.R
/embed-env/lib/R/library/tcltk/demo/tkdensity.R
/embed-env/lib/R/library/tcltk/demo/tkfaq.R
/embed-env/lib/R/library/tcltk/demo/tkttest.R
/embed-env/lib/R/library/tcltk/exec/Tk-frontend.R
/embed-env/lib/R/library/tcltk/exec/console.tcl
/embed-env/lib/R/library/tcltk/exec/hierarchy.tcl
/embed-env/lib/R/library/tcltk/exec/pkgIndex.tcl
/embed-env/lib/R/library/tcltk/exec/progressbar.tcl
/embed-env/lib/R/library/tcltk/exec/util-dump.tcl
/embed-env/lib/R/library/tcltk/exec/util-expand.tcl
/embed-env/lib/R/library/tcltk/exec/util-number.tcl
/embed-env/lib/R/library/tcltk/exec/util-string.tcl
/embed-env/lib/R/library/tcltk/exec/util-tk.tcl
/embed-env/lib/R/library/tcltk/exec/util.tcl
/embed-env/lib/R/library/tcltk/exec/widget.tcl
/embed-env/lib/R/library/tcltk/help/AnIndex
/embed-env/lib/R/library/tcltk/help/aliases.rds
/embed-env/lib/R/library/tcltk/help/paths.rds
/embed-env/lib/R/library/tcltk/help/tcltk.rdb
/embed-env/lib/R/library/tcltk/help/tcltk.rdx
/embed-env/lib/R/library/tcltk/html/00Index.html
/embed-env/lib/R/library/tcltk/html/R.css
/embed-env/lib/R/library/tools/DESCRIPTION
/embed-env/lib/R/library/tools/INDEX
/embed-env/lib/R/library/tools/Meta/Rd.rds
/embed-env/lib/R/library/tools/Meta/features.rds
/embed-env/lib/R/library/tools/Meta/hsearch.rds
/embed-env/lib/R/library/tools/Meta/links.rds
/embed-env/lib/R/library/tools/Meta/nsInfo.rds
/embed-env/lib/R/library/tools/Meta/package.rds
/embed-env/lib/R/library/tools/NAMESPACE
/embed-env/lib/R/library/tools/R/sysdata.rdb
/embed-env/lib/R/library/tools/R/sysdata.rdx
/embed-env/lib/R/library/tools/R/tools
/embed-env/lib/R/library/tools/R/tools.rdb
/embed-env/lib/R/library/tools/R/tools.rdx
/embed-env/lib/R/library/tools/help/AnIndex
/embed-env/lib/R/library/tools/help/aliases.rds
/embed-env/lib/R/library/tools/help/paths.rds
/embed-env/lib/R/library/tools/help/tools.rdb
/embed-env/lib/R/library/tools/help/tools.rdx
/embed-env/lib/R/library/tools/html/00Index.html
/embed-env/lib/R/library/tools/html/R.css
/embed-env/lib/R/library/tools/libs/tools.so
/embed-env/lib/R/library/translations/DESCRIPTION
/embed-env/lib/R/library/utils/DESCRIPTION
/embed-env/lib/R/library/utils/INDEX
/embed-env/lib/R/library/utils/Meta/Rd.rds
/embed-env/lib/R/library/utils/Meta/features.rds
/embed-env/lib/R/library/utils/Meta/hsearch.rds
/embed-env/lib/R/library/utils/Meta/links.rds
/embed-env/lib/R/library/utils/Meta/nsInfo.rds
/embed-env/lib/R/library/utils/Meta/package.rds
/embed-env/lib/R/library/utils/NAMESPACE
/embed-env/lib/R/library/utils/R/sysdata.rdb
/embed-env/lib/R/library/utils/R/sysdata.rdx
/embed-env/lib/R/library/utils/R/utils
/embed-env/lib/R/library/utils/R/utils.rdb
/embed-env/lib/R/library/utils/R/utils.rdx
/embed-env/lib/R/library/utils/Sweave/Sweave-test-1.Rnw
/embed-env/lib/R/library/utils/Sweave/example-1.Rnw
/embed-env/lib/R/library/utils/doc/Sweave.pdf
/embed-env/lib/R/library/utils/help/AnIndex
/embed-env/lib/R/library/utils/help/aliases.rds
/embed-env/lib/R/library/utils/help/paths.rds
/embed-env/lib/R/library/utils/help/utils.rdb
/embed-env/lib/R/library/utils/help/utils.rdx
/embed-env/lib/R/library/utils/html/00Index.html
/embed-env/lib/R/library/utils/html/R.css
/embed-env/lib/R/library/utils/iconvlist
/embed-env/lib/R/library/utils/libs/utils.so
/embed-env/lib/R/library/utils/misc/exDIF.csv
/embed-env/lib/R/library/utils/misc/exDIF.dif
/embed-env/lib/R/library/cli/DESCRIPTION
/embed-env/lib/R/library/cli/INDEX
/embed-env/lib/R/library/cli/LICENSE
/embed-env/lib/R/library/cli/Meta/Rd.rds
/embed-env/lib/R/library/cli/Meta/features.rds
/embed-env/lib/R/library/cli/Meta/hsearch.rds
/embed-env/lib/R/library/cli/Meta/links.rds
/embed-env/lib/R/library/cli/Meta/nsInfo.rds
/embed-env/lib/R/library/cli/Meta/package.rds
/embed-env/lib/R/library/cli/NAMESPACE
/embed-env/lib/R/library/cli/NEWS.md
/embed-env/lib/R/library/cli/R/cli
/embed-env/lib/R/library/cli/R/cli.rdb
/embed-env/lib/R/library/cli/R/cli.rdx
/embed-env/lib/R/library/cli/R/sysdata.rdb
/embed-env/lib/R/library/cli/R/sysdata.rdx
/embed-env/lib/R/library/cli/examples/apps/news.R
/embed-env/lib/R/library/cli/examples/apps/outdated.R
/embed-env/lib/R/library/cli/examples/apps/search.R
/embed-env/lib/R/library/cli/examples/apps/up.R
/embed-env/lib/R/library/cli/exec/news.R
/embed-env/lib/R/library/cli/exec/outdated.R
/embed-env/lib/R/library/cli/exec/search.R
/embed-env/lib/R/library/cli/exec/up.R
/embed-env/lib/R/library/cli/help/AnIndex
/embed-env/lib/R/library/cli/help/aliases.rds
/embed-env/lib/R/library/cli/help/cli.rdb
/embed-env/lib/R/library/cli/help/cli.rdx
/embed-env/lib/R/library/cli/help/figures/demo-spinners.svg
/embed-env/lib/R/library/cli/help/figures/get-spinner.svg
/embed-env/lib/R/library/cli/help/figures/make-spinner-custom.svg
/embed-env/lib/R/library/cli/help/figures/make-spinner-default.svg
/embed-env/lib/R/library/cli/help/figures/make-spinner-template.svg
/embed-env/lib/R/library/cli/help/figures/progress-1.svg
/embed-env/lib/R/library/cli/help/figures/progress-after.svg
/embed-env/lib/R/library/cli/help/figures/progress-along-1.svg
/embed-env/lib/R/library/cli/help/figures/progress-along-2.svg
/embed-env/lib/R/library/cli/help/figures/progress-along-3.svg
/embed-env/lib/R/library/cli/help/figures/progress-clear.svg
/embed-env/lib/R/library/cli/help/figures/progress-current.svg
/embed-env/lib/R/library/cli/help/figures/progress-format.svg
/embed-env/lib/R/library/cli/help/figures/progress-message.svg
/embed-env/lib/R/library/cli/help/figures/progress-natotal.svg
/embed-env/lib/R/library/cli/help/figures/progress-output.svg
/embed-env/lib/R/library/cli/help/figures/progress-output2.svg
/embed-env/lib/R/library/cli/help/figures/progress-step-dynamic.svg
/embed-env/lib/R/library/cli/help/figures/progress-step-msg.svg
/embed-env/lib/R/library/cli/help/figures/progress-step-spin.svg
/embed-env/lib/R/library/cli/help/figures/progress-step.svg
/embed-env/lib/R/library/cli/help/figures/progress-tasks.svg
/embed-env/lib/R/library/cli/help/paths.rds
/embed-env/lib/R/library/cli/html/00Index.html
/embed-env/lib/R/library/cli/html/R.css
/embed-env/lib/R/library/cli/include/cli/progress.h
/embed-env/lib/R/library/cli/libs/cli.so
/embed-env/lib/R/library/cli/logo.txt
/embed-env/lib/R/library/cli/shiny/along/app.R
/embed-env/lib/R/library/cli/shiny/format/app.R
/embed-env/lib/R/library/cli/shiny/nested/app.R
/embed-env/lib/R/library/cli/shiny/output/app.R
/embed-env/lib/R/library/cli/shiny/simple/app.R
/embed-env/lib/R/library/rlang/DESCRIPTION
/embed-env/lib/R/library/rlang/INDEX
/embed-env/lib/R/library/rlang/LICENSE
/embed-env/lib/R/library/rlang/Meta/Rd.rds
/embed-env/lib/R/library/rlang/Meta/features.rds
/embed-env/lib/R/library/rlang/Meta/hsearch.rds
/embed-env/lib/R/library/rlang/Meta/links.rds
/embed-env/lib/R/library/rlang/Meta/nsInfo.rds
/embed-env/lib/R/library/rlang/Meta/package.rds
/embed-env/lib/R/library/rlang/NAMESPACE
/embed-env/lib/R/library/rlang/NEWS.md
/embed-env/lib/R/library/rlang/R/rlang
/embed-env/lib/R/library/rlang/R/rlang.rdb
/embed-env/lib/R/library/rlang/R/rlang.rdx
/embed-env/lib/R/library/rlang/backtrace-ver
/embed-env/lib/R/library/rlang/help/AnIndex
/embed-env/lib/R/library/rlang/help/aliases.rds
/embed-env/lib/R/library/rlang/help/figures/lifecycle-archived.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-defunct.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-deprecated.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-experimental.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-maturing.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-questioning.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-retired.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-soft-deprecated.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-stable.svg
/embed-env/lib/R/library/rlang/help/figures/lifecycle-superseded.svg
/embed-env/lib/R/library/rlang/help/figures/logo.png
/embed-env/lib/R/library/rlang/help/paths.rds
/embed-env/lib/R/library/rlang/help/rlang.rdb
/embed-env/lib/R/library/rlang/help/rlang.rdx
/embed-env/lib/R/library/rlang/html/00Index.html
/embed-env/lib/R/library/rlang/html/R.css
/embed-env/lib/R/library/rlang/libs/rlang.so
/embed-env/lib/R/library/evaluate/DESCRIPTION
/embed-env/lib/R/library/evaluate/INDEX
/embed-env/lib/R/library/evaluate/LICENSE
/embed-env/lib/R/library/evaluate/Meta/Rd.rds
/embed-env/lib/R/library/evaluate/Meta/features.rds
/embed-env/lib/R/library/evaluate/Meta/hsearch.rds
/embed-env/lib/R/library/evaluate/Meta/links.rds
/embed-env/lib/R/library/evaluate/Meta/nsInfo.rds
/embed-env/lib/R/library/evaluate/Meta/package.rds
/embed-env/lib/R/library/evaluate/NAMESPACE
/embed-env/lib/R/library/evaluate/NEWS.md
/embed-env/lib/R/library/evaluate/R/evaluate
/embed-env/lib/R/library/evaluate/R/evaluate.rdb
/embed-env/lib/R/library/evaluate/R/evaluate.rdx
/embed-env/lib/R/library/evaluate/help/AnIndex
/embed-env/lib/R/library/evaluate/help/aliases.rds
/embed-env/lib/R/library/evaluate/help/evaluate.rdb
/embed-env/lib/R/library/evaluate/help/evaluate.rdx
/embed-env/lib/R/library/evaluate/help/paths.rds
/embed-env/lib/R/library/evaluate/html/00Index.html
/embed-env/lib/R/library/evaluate/html/R.css
/embed-env/lib/R/modules/lapack.so
/embed-env/lib/R/COPYING
/embed-env/lib/R/SVN-REVISION
`
